# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 3D Движок
email: ig.samsonov10@yandex.ru
description: >- # this means to ignore newlines until "baseurl:"
  Технический дневник разработки 3D игрового движка с нуля на C++ и OpenGL
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Minuta18

theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme 

nav_pages:
  - title: "О сайте"
    url: "/about"

favicon_ico: "/assets/images/favicon.png"

aux_links:
  "Github проекта":
    - "//github.com/Minuta18-s-3D-engine"

nav_external_links:
  - title: Github проекта
    url: https://github.com/Minuta18-s-3D-engine
    opens_in_new_tab: true

aux_links_new_tab: false

mermaid:
  version: "9.1.3"

last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y"

footer_content: |
  Контент этого сайта доступен под лицензией 
  <a href="https://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International
  </a> 
  © 2026 Minuta18

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
